# BRITE configuration file for AS-level Barabasi-Albert topology

BriteConfig

BeginModel
	Name = 10    # AS-level Barabasi-Albert (ModelConstants.AS_BARABASI)
	N = 50     # Number of nodes
	HS = 1000   # Size of high-level square
	LS = 100    # Size of low-level square
	NodePlacement = 1   # Heavy tailed node placement
	GrowthType = 1      # Incremental growth
	m = 4              # Number of edges added per node
	BWDist = 1         # Constant bandwidth
	BWMin = 1000.0       # Minimum bandwidth
	BWMax = 10000.0      # Maximum bandwidth
	p = 0.15            # Probability of connecting to high-degree nodes
	q = 0.2            # Probability of connecting to low-degree nodes
EndModel

BeginOutput
	BRITE = 1         # BRITE format
	OTTER = 0         # No OTTER format
	DML = 0           # No DML format
	NS = 0            # No NS format
	Javasim = 0       # No Javasim format
EndOutput