# BRITE configuration file for Top-Down Hierarchical Topology
# AS Level: Barabasi-Albert (Model 4)
# Router Level: Barabasi-Albert (Model 2)

BriteConfig

BeginModel
    Name = 5             # Top Down = 5
    edgeConn = 1         # Random=1, Smallest Nonleaf=2, Smallest Deg=3, k-Degree=4
    k = -1               # Only needed if edgeConn is set to K-Degree, otherwise use -1
    BWInter = 1          # Constant=1, Uniform=2, HeavyTailed=3, Exponential=4
    BWInterMin = 10.0
    BWInterMax = 1024.0
    BWIntra = 1          # Constant=1, Uniform=2, HeavyTailed=3, Exponential=4
    BWIntraMin = 10.0
    BWIntraMax = 1024.0
EndModel

BeginModel
    Name = 10             # AS Barabasi = 4
    N = 5               # Number of AS nodes in the global graph
    HS = 1000            # Size of main plane (number of squares)
    LS = 100             # Size of inner planes (number of squares)
    NodePlacement = 1    # Random = 1, Heavy Tailed = 2
    GrowthType = 1       # Incremental = 1, All = 2
    m = 1                # Number of neighboring nodes each new node connects to
    BWDist = 1           # Constant = 1, Uniform = 2, HeavyTailed = 3, Exponential = 4
    BWMin = 10.0
    BWMax = 1024.0
	p = 0.15              # Probability of adding a link between two existing nodes (used only if GrowthType=1)
	q = 0.2               # Probability of rewiring a link from an existing node to another existing node (used only if GrowthType=1)
EndModel

BeginModel
    Name = 9             # Router Barabasi = 9
    N = 10               # Number of routers INSIDE each AS
    HS = 1000            # Size of main plane (number of squares)
    LS = 100             # Size of inner planes (number of squares)
    NodePlacement = 1    # Random = 1, Heavy Tailed = 2
    GrowthType = 1       # Incremental = 1, All = 2
    m = 4                # Number of neighboring nodes each new node connects to
    BWDist = 1           # Constant = 1, Uniform = 2, HeavyTailed = 3, Exponential = 4
    BWMin = 10.0
    BWMax = 1024.0
	p = 0.15              # Probability of adding a link between two existing nodes (used only if GrowthType=1)
	q = 0.2               # Probability of rewiring a link from an existing node to another existing node (used only if GrowthType=1)
EndModel

BeginOutput
    BRITE = 1            # 1 = save as BRITE, 0 = Do not save
    OTTER = 0            # 1/0 = enable/disable output to Otter
    DML = 0              # 1/0 = enable/disable output to SSFNet's DML format
    NS = 0               # 1/0 = enable/disable output to NS-2
    Javasim = 0          # 1/0 = enable/disable output to Javasim
EndOutput